Add recordings/compositions endpoint
COALAIP/omi-mvi-1.0 pull request #27
Opened 2017-05-07 22:01 UTC by vrde

Add `recordings/compositions` endpoint to:
- Create new connections between recordings and compositions using the `isrc` and `iswc` codes.
- Retrieve recordings connected to a composition.
- Retrieve compositions connected to a recording.

2017-05-08 13:19 UTC, TimDaub commented on omi_api/views/compositions.py
> +        parser.add_argument('iswc', type=str, required=True,
I'll make `required=False`. However, then matching recordings and compositions won't work for this implementation.

@vrde and I talked.

2017-05-08 13:51 UTC, TimDaub commented on omi_api/queries.py
> +    return doc['block']['transactions']['asset']['data']
For prosperity: One must be able to do this in a MDB query directly :thinking:

2017-05-08 13:55 UTC, TimDaub commented on omi_api/utils.py
> +        if v:
Oh thanks! I remember to think about this during implementation. Then I forgot.

2017-05-08 14:09 UTC, TimDaub commented on omi_api/views/recordings_compositions.py
> +
rm line? @vrde I can do it; or was it intentional?

2017-05-08 14:11 UTC, TimDaub commented on omi_api/views/recordings_compositions.py
> +recordings_compositions_api.add_resource(
We also need an `/compositions/recordings` endpoint. I imagine that is not a lot of work (same functionality can be reused).

2017-05-08 14:11 UTC, vrde commented on omi_api/views/recordings_compositions.py
> +
Oh remove it.

2017-05-08 14:13 UTC, TimDaub commented on omi_api/views/recordings_compositions.py
> +                signers=config.PUBLIC_KEY,
When #26 is merged, we should adjust this.

2017-05-08 14:13 UTC, TimDaub commented on omi_api/views/recordings_compositions.py
> +        signed_tx = bdb.transactions.fulfill(tx, private_keys=config.PRIVATE_KEY)
When #26 is merged, we should adjust this.

2017-05-08 14:13 UTC, vrde commented on omi_api/views/recordings_compositions.py
> +recordings_compositions_api.add_resource(
It's not a lot of work, it's actually just one line to implement this. I didn't do it yet because I didn't want to diverge from the specs too much.

2017-05-08 14:15 UTC, TimDaub requested changes
Please add documentation in Readme.md.

Other than that: Great work!

2017-07-25 08:09 UTC, TimDaub approved these changes

2017-07-25 08:09 UTC, merged